const items = [
  {
    id: 100,
    title: 'Ribeye',
    category: 'Course',
    price: 2,
    img: './images/ribeye.JPG',
    desc: `appetizer, sous vide or butter based prime ribeye 22 oz, potatoes, dessert`,
  },
  {
    id: 102,
    title: 'Filet Mingnon',
    category: 'Course',
    price: 2,
    img: './images/filet.JPG',
    desc: `appetizer, sous vide or butter based prime filet 10 oz, potatoes, dessert`,
  },
  {
    id: 103,
    title: 'Rissoto',
    category: 'Entree',
    price: 1,
    img: './images/rissotto.JPG',
    desc: `shallots, pinot grigio, seared scallop, herb butter`,
  },
  {
    id: 104,
    title: 'Pesto',
    category: 'Entree',
    price: 1,
    img: './images/pesto.JPG',
    desc: `parsley, pine nuts, garlic, rigatonni, chicken thigh`,
  },
  {
    id: 105,
    title: 'Stekki-Don',
    category: 'Entree',
    price: 1,
    img: './images/stekki.JPG',
    desc: `sous vide ribeye 12 oz, stekki sauce, onions, egg, rice`,
  },
  {
    id: 106,
    title: 'Lamb',
    category: 'Course',
    price: 2,
    img: './images/lamb.JPG',
    desc: `appetizer, garlic herb crusted racknpotatoes, dessert`,
  },
  {
    id: 107,
    title: 'Chinese New Year',
    category: 'Course',
    price: 6,
    img: './images/cny.JPG',
    desc: `ginger scallion lobster, crab, clams, striped bass, mushrooms, chicken`,
  },
];
const point = [
  {
    id: 1,
    title: 'Nicole',
    category: 'Point System',
    price: 1000000000000,
    img: './images/profile.jpeg',
    desc: `organ tare tare, blood, marrow, diabetes, cholesterol , back pain`,
  },
  {
    id: 2,
    title: 'Silvan',
    category: 'Point System',
    price: 4,
    img: './images/profile.jpeg',
    desc: `organ tare tare, blood, marrow, diabetes, cholesterol , back pain`,
  },
  {
    id: 3,
    title: 'Darren',
    category: 'Point System',
    price: 2,
    img: './images/profile.jpeg',
    desc: `organ tare tare, blood, marrow, diabetes, cholesterol , back pain`,
  },
  {
    id: 4,
    title: 'Chris',
    category: 'Point System',
    price: 3,
    img: './images/profile.jpeg',
    desc: `organ tare tare, blood, marrow, diabetes, cholesterol , back pain`,
  },
  {
    id: 5,
    title: 'Jason',
    category: 'Point System',
    price: 3,
    img: './images/profile.jpeg',
    desc: `organ tare tare, blood, marrow, diabetes, cholesterol , back pain`,
  },
  {
    id: 6,
    title: 'Cici',
    category: 'Point System',
    price: 1,
    img: './images/profile.jpeg',
    desc: `organ tare tare, blood, marrow, diabetes, cholesterol , back pain`,
  },
  {
    id: 7,
    title: 'Lee',
    category: 'Point System',
    price: 0,
    img: './images/profile.jpeg',
    desc: `organ tare tare, blood, marrow, diabetes, cholesterol , back pain`,
  },
  {
    id: 7,
    title: 'Alan',
    category: 'Point System',
    price: 1,
    img: './images/profile.jpeg',
    desc: `organ tare tare, blood, marrow, diabetes, cholesterol , back pain`,
  },
];
const menu = [...items, ...point]
export default menu;
